# Thông tin Server
server.port=8086
spring.application.name=inventory-service

# Cấu hình Database (Dùng chung DB EcommerceDB với các service khác)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.url=jdbc:sqlserver://mssql-clusterip-srv:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
#spring.datasource.password=pa55w0rd!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate tự động sinh bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cấu hình RabbitMQ
spring.rabbitmq.host=localhost
#spring.rabbitmq.host=rabbitmq-clusterip-srv
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest