server.port=8084
spring.application.name=order-service

# Cấu hình kết nối SQL Server trên Windows (giống Customer Service)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.url=jdbc:sqlserver://mssql-clusterip-srv:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
# spring.datasource.password=pa55w0rd!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Cấu hình cho gRPC Client biết Server đang nằm ở đâu
grpc.client.catalog-service.address=static://localhost:9090
#grpc.client.catalog-service.address=static://catalog-srv:9090
grpc.client.catalog-service.negotiation-type=plaintext
# Cấu hình RabbitMQ
spring.rabbitmq.host=localhost
#spring.rabbitmq.host=rabbitmq-clusterip-srv
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Khóa bí mật dùng để giải mã JWT (BẮT BUỘC PHẢI GIỐNG HỆT BÊN AUTH-SERVICE)
jwt.secret=very_secret_key_for_ecommerce_app_do_not_share
jwt.expiration=86400000