server.port=8085
spring.application.name=auth-service

# Kết nối chung với Database của hệ thống
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.url=jdbc:sqlserver://mssql-clusterip-srv:1433;databaseName=EcommerceDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
#spring.datasource.password=pa55w0rd!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Từ khóa bí mật dùng để ký Token (Tuyệt đối không để lộ)
jwt.secret=very_secret_key_for_ecommerce_app_do_not_share
# Thời gian sống của Token (Ví dụ: 86400000 mili-giây = 1 ngày)
jwt.expiration=86400000
